# Site settings
title: Studyworth
email: me@oskarth.com
description: > # this means to ignore newlines until "baseurl:"
  This is a space for my amateur math writing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://math.oskarth.com" # the base hostname & protocol for your site
twitter_username: oskarth
github_username:  oskarth
permalink: /:title

# Build settings
markdown: kramdown
